name: Prepare Uberjar Artifact
runs:
  using: "composite"
  steps:
    - name: Mark with the commit hash
      run: git rev-parse --short HEAD > COMMIT-ID
    - name: Calculate SHA256 checksum
      shell: bash
      run: sha256sum ./target/uberjar/metabase.jar > SHA256.sum
    - name: Upload JARs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: metabase-${{ matrix.edition }}-uberjar
        path: |
          ./target/uberjar/metabase.jar
          ./COMMIT-ID
          ./SHA256.sum
